---
- name: Instalar apache2
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Copiar plantilla de index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Reiniciar apache

- name: Habilitar y arrancar apache2
  service:
    name: apache2
    state: started
    enabled: yes
